apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-redis
        image: redis:alpine  # Redis image with redis-cli
        command:
        - sh
        - -c
        - "until redis-cli -h $REDIS_HOST -p $REDIS_PORT ping; do echo waiting for Redis; sleep 2; done"
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: REDIS_PORT
      containers:
      - name: backend
        image: docker.io/yiadh/backend:1.0.0
        env:
        # We need to make make a change on the backend source code
        # in order to make the Redis url and port customizable
        # in https://github.com/slgevens/example-falcon/blob/main/main.go#L15
        # by loading the environment variables REDIS_HOST and REDIS_PORT
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: REDIS_PORT
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6399"
